reorder_imports = true
max_width = 80
use_small_heuristics = "max"
wrap_comments = false
use_try_shorthand = true
use_field_init_shorthand = true
struct_lit_single_line = true
reorder_modules = true
overflow_delimited_expr = true
normalize_doc_attributes = false
match_block_trailing_comma = true
inline_attribute_width = 80
format_strings = true
fn_single_line = true
#fn_params_layout = "compressed"
